### ISSUE TITLE
Omdb request crash

### ISSUE THREAD

**Issue by dehernandez7791** [FatBrownies/CinemaBase#1]
App crashed when JSON request is made for movies that are not formatted properly. Example type Red October into search bar when request is made app crashes.

**Comment by romero4742** [comment]
thanks dude I'll fix it

Victor Romero

**Comment by dehernandez7791** [comment]
hey dude we have to publish by tonight we need to Skype it. Please call me
asap.

On Fri, May 8, 2015 at 5:59 PM, romero4742 notifications@github.com wrote:

> thanks dude I'll fix it
> 
> Victor Romero
> 
> On 08/05/2015, at 04:49 p.m., "dehernandez7791" notifications@github.com
> wrote:
> 
> > App crashed when JSON request is made for movies that are not formatted
> > properly. Example type Red October into search bar when request is made app
> > crashes.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FatBrownies/CinemaBase/issues/1#issuecomment-100403830
> .

## 

_Daniel Hernandez_
Computer Science, 2015
_California State Polytechnic University, Pomona_
dehernandez@cpp.edu
310.977.0622

**Comment by dehernandez7791** [comment]
Reopened issue as bug
